services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ubl\Supportchat\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Ubl\Supportchat\Library\Chat:
    public: true